name: Deploy Worker
env:
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  WRANGLER_TOML: "wrangler.toml"

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.2.0
          run_install: true
      - name: Install Wrangler
        run: pnpm add --global wrangler
      - name: Build & Deploy Worker
        working-directory: workers/core
        run: wrangler deploy --config ${{ env.WRANGLER_TOML }}
